P8105 HW 2
================
Haley Zylberberg

Will first call in tidyverse and readxl libraries.

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

## Problem 2: Clean Trash Wheel Datasets

This problem uses the dataset Trash Wheel which includes data regarding
trash that was removed from the Inner Harbor in Baltimore, Maryland.

First, import Trash Wheel dataset, specifically sheet Mr Trash Wheel,
and clean. We need to skip column 1 as it contains pictures, not include
blank columns, and also not import the last row as it includes data
summary elements. We also need to convert dumpert variable to numeric as
it is coded as characters. And finally, we need to pivot the trash types
in order to make a tidy dataset.

``` r
mr_trash_df = 
  read_excel("data/202207 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel", skip = 1, range = cell_cols(1:14)) |> 
  janitor::clean_names() |>
  subset(!is.na(dumpster) & dumpster != "") |>
  mutate(trash_wheel = "Mr", year = as.numeric(year)) |> 
  relocate(trash_wheel) |>
   pivot_longer(
    plastic_bottles:sports_balls,
    names_to = "litter_type",
    values_to = "litter_amount"
  )
```

Calculate new homes powered column based on note that 1 ton garbage =
500KW of electricity and 30KW powers 1 house.

``` r
mr_trash_df = 
mutate (mr_trash_df, homes_powered = (weight_tons*500)/30)
```

Next, import Prof. Trash Wheel dataset, clean, and create new
homes_powered variable.

``` r
prof_trash_df = 
  read_excel("data/202207 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel", skip = 1, range = cell_cols(1:13)) |> 
  janitor::clean_names() |>
  subset(!is.na(dumpster) & dumpster != "") |>
  mutate(trash_wheel = "Prof", year = as.numeric(year)) |> 
  relocate(trash_wheel) |>
   pivot_longer(
    plastic_bottles:chip_bags,
    names_to = "litter_type",
    values_to = "litter_amount"
  ) |>
mutate (homes_powered = (weight_tons*500)/30)
```

Next, import Gwynnda Trash Wheel dataset, clean, and create new
homes_powered variable.

``` r
gwynnda_trash_df = 
  read_excel("data/202207 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda Trash Wheel", skip = 1, range = cell_cols(1:11)) |> 
  janitor::clean_names() |>
  subset(!is.na(dumpster) & dumpster != "") |>
  mutate(trash_wheel = "Gwynnda", year = as.numeric(year)) |> 
  relocate(trash_wheel) |>
   pivot_longer(
    plastic_bottles:plastic_bags,
    names_to = "litter_type",
    values_to = "litter_amount"
  ) |>
mutate (homes_powered = (weight_tons*500)/30)
```

Combine all 3 trash wheels dataframes.

``` r
trash_wheel_df = 
  bind_rows(mr_trash_df, prof_trash_df, gwynnda_trash_df)
```

The dataframe Trash Wheel consists of combined data from Mister Trash
Wheel, Professor Trash Wheel and Gwynnda Trash Wheel and detailes the
weight of trash and type of trash that these wheels have collected from
2014 to 2022. There are 4817 observations. The variables in the
dataframe are trash_wheel, dumpster, month, year, date, weight_tons,
volume_cubic_yards, homes_powered, litter_type, litter_amount. The types
of litter collected are plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, grocery_bags, chip_bags, sports_balls, plastic_bags. The
total weight of trash collected by Professor Trash Wheel is 190.12. The
total weight of trash collected by Mr. Trash Wheel is 1748.36. And the
total weight of trash collected by Gwynnda Trash Wheel is 308.42. Mr
Trash Wheel powered 53.2711761 homes on average, Professor Trash Wheel
powered 33.7092199 on average, and Gwynnda Trash Wheel powered
48.8647799 homes on average. The total number of cigarette butts
collected by Gwynnda Trash Wheel in July 2021 was 1.63^{4}.

## Problem 3

This problem includes the dataset MCI and amyloid which was collcted as
part of an observation study and incldues biomarkers from patients who
developed Alzheimer’s disease, as measured by development of mild
cognitive impairment (MCI).

First import MCI and begin the cleaning process. Will skip the first row
as this contains notes about the dataset. Recode age to be male (0) vs
female (1) and presence of apoe4 as carrier (1) vs non_carrier (0).
Rename education to education_years, to specify the measurement of the
variable. Change”.” to missing values (i.e. NA) in age_at_onset
variable.

``` r
MCI_df = 
  read_csv("data/MCI_baseline.csv", skip = 1) |> 
  janitor::clean_names() |>
mutate(
 sex = case_match(
    sex, 1 ~ 'female', 0 ~ 'male'),
 apoe4 = case_match(
   apoe4, 1 ~ "carrier",0 ~ "non_carrier"),
 age_at_onset = ifelse(
   age_at_onset == ".", NA, age_at_onset)
 ) |>
  rename (education_years = education)|> 
  subset(!is.na(current_age) & current_age != "",
         !is.na(age_at_onset) & age_at_onset != "")
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The study recruited 483 participants. The average age of all
participants at baseline was 65.0467909. There are 272 females and 211
males. The average education in years of all participants is 16.3975155.
The proportion of women who are apoe4 carriers are 0.3014706 and the
proportion of men who are apoe4 carriers are 0.2985782.

However, only 97 participants developed MCI. Will remove these
participants as the study goal was to include patients who developed
MCI.And then redo data description.

``` r
MCI_df = 
na.omit(MCI_df)
```

The average age of participants with MCI at baseline was 65.6113402.
There are 51 females with MCI and 46 males with MCI. The average
education in years of participants with MCI is 16.5360825. Among
participants with MCI, the proportion of women who are apoe4 carriers
are 0.6078431 and the proportion of men who are apoe4 carriers are
0.6521739.

First import the amyloid biomarkers dataset and begin the cleaning
process. This dataset includes time since amyloid was measured. Will
skip the first row as this contains notes about the dataset. Rename
baseline to time_0. Then pivot data so that each variable has its own
column.

``` r
amyloid_df = 
  read_csv("data/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
    rename (time_0 = baseline) |>
pivot_longer(
    time_0:time_8,
    names_to = "time",
    values_to = "time_values"
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

This dataset contains data on for 487 participants. However, there are
140 participants with at least 1 missing time value.

Next will determine whether some participants are only present in one
dataset.
